name: Playwright Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"
      - .devcontainer/devcontainer.json

  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"
      - .devcontainer/devcontainer.json

permissions:
  contents: read
  actions: write

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install node & pnpm
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          version: 2026.6.10 # mise の version も固定する
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build check
        run: pnpm build
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
